#!/bin/bash
#
# check_zimbra_backup - nagios plugin
#
# Copyright (c) 2014 Denis Sacchet
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source /usr/lib/nagios/plugins/utils.sh

if [ $(id -un) != 'zimbra' ]
then
	echo "ERROR - Must be run under zimbra user"
	exit $STATE_UNKNOWN
fi

last_incr=$(date --date "$(/opt/zimbra/bin/zmbackupquery  | egrep -B 2 "Status:.*completed" | egrep -B 1 "Type:.*incremental" | head -n 1 | cut -d '-' -f 2 | sed 's@\(....\)\(..\)\(..\)\.\(..\)\(..\)\(..\).*@\1-\2-\3 \4:\5:\6@')" +%s)
last_full=$(date --date "$(/opt/zimbra/bin/zmbackupquery  | egrep -B 2 "Status:.*completed" | egrep -B 1 "Type:.*full" | head -n 1 | cut -d '-' -f 2 | sed 's@\(....\)\(..\)\(..\)\.\(..\)\(..\)\(..\).*@\1-\2-\3 \4:\5:\6@')" +%s)
now=$(date +%s)

full_age=$(((${now}-${last_full})/86400))
incr_age=$(((${now}-${last_incr})/86400))

CODE_RETOUR=$STATE_OK
STATUS=OK

MESSAGE="Last full backup is $full_age days old / Last incremental backup is $incr_age days old"

if [ $full_age -gt 7 -o $incr_age -gt 1 ]
then
	CODE_RETOUR=$STATE_CRITICAL
	STATUS='CRITICAL'
fi

echo "$STATUS - $MESSAGE"
exit $CODE_RETOUR
